version: '3.8'
volumes:
  projectdata:
  tailscale:
  sccache:
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/rust:1-1-bullseye
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - sccache:/sccache
      - projectdata:/var/lib/gnosco
    command: sleep infinity
    environment:
      - RUSTC_WRAPPER=sccache
      - SCCACHE_DIR=/sccache
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - RUST_LIB_BACKTRACE=1
      - HTTP_PORT=6100
      - TZ=America/New_York
      - DATABASE_URL=sqlite:///workspace/database.db

  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/run/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:gnosco
    volumes:
      - tailscale:/var/run/tailscale
